name: 'gatekeeper'

services:
  db:
    image: postgres:16.3
    env_file:
      - ./db_env.list
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - kong-net

networks:
  kong-net: